# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
env:
  global:
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j1
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
    - ROS_DISTRO="kinetic"  UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/callemein/ROS_QT_Example/.travis.rosinstall
install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y qt5-default 
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - travis_wait 30 .ci_config/travis.sh 

